name: 'Arturo Bundler'
description: 'Bundle Arturo applications as executable binaries'
inputs:
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    arch:
        description: >-
            The architecture to build for.
            (one of: 'x86', 'arm', 'arm64', 'amd64', 'native')
        default: 'native'
    entry: 
        description: >-
            Entry file for the executable.
        required: true
runs:
    using: "composite"
    steps:
        - name: Install Arturo
          uses: arturo-lang/arturo-action@main
          with: 
            token: ${{ inputs.token }}
            arch: ${{ inputs.arch }}

        - name: Generate executable (*nix)
          if: runner.os != 'Windows'
          run: |
            arturo --bundle ${{ inputs.entry }}
            entry="${{ inputs.entry }}"
            xbase=${entry##*/}
            xpref=${xbase%.*}
            sudo chmod +x $xpref
          shell: bash

        - name: Generate executable (Windows)
          if: runner.os == 'Windows'
          run: |
            # mkdir nim
            # curl -L https://nim-lang.org/download/nim-2.0.4_x64.zip -o dist/nim.zip
            # 7z x dist/nim.zip -onim
            export PATH="${{ github.workspace }}/nim/nim-2.0.4/bin":$PATH

            arturo --bundle ${{ inputs.entry }}
            entry="${{ inputs.entry }}"
            xbase=${entry##*/}
            xpref=${xbase%.*}
            sudo chmod +x $xpref
          shell: msys2 {0}

branding:
    icon: 'package'
    color: 'purple'
    