name: 'Arturo Bundler'
description: 'Bundle Arturo applications as executable binaries'
inputs:
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    arch:
        description: >-
            The architecture to build for.
            (one of: 'x86', 'arm', 'arm64', 'amd64', 'native')
        default: 'native'
    entry: 
        description: >-
            Entry file for the executable.
        required: true
    target:
        description: >-
            The name of the final binary.
        default: 'auto'
runs:
    using: "composite"
    steps:
        - name: Install Arturo
          uses: arturo-lang/arturo-action@main
          with: 
            token: ${{ inputs.token }}
            arch: ${{ inputs.arch }}

        - name: Generate executable (*nix)
          if: runner.os != 'Windows'
          run: |
            if [ "${{ inputs.target }}" = "auto" ]; then
                arturo --bundle ${{ inputs.entry }}
                entry="${{ inputs.entry }}"
                xbase=${entry##*/}
                xpref=${xbase%.*}
                sudo chmod +x $xpref

                echo "EXEFILE=$xpref" >> $GITHUB_ENV
            else
                arturo --bundle --as:${{ inputs.target }} ${{ inputs.entry }}
                sudo chmod +x ${{ inputs.target }}

                echo "EXEFILE=${{ inputs.target }}" >> $GITHUB_ENV
            fi
          shell: bash

        - name: Generate executable (Windows)
          if: runner.os == 'Windows'
          run: |
            export PATH="${{ github.workspace }}/nim/nim-2.0.4/bin":$PATH
            if [ "${{ inputs.target }}" = "auto" ]; then
                arturo --bundle ${{ inputs.entry }}
                entry="${{ inputs.entry }}"
                xbase=${entry##*/}
                xpref=${xbase%.*}
                echo "XPREF = $xpref"
            else
                arturo --bundle --as:${{ inputs.target }} ${{ inputs.entry }}
                echo "EXEFILE=${{ inputs.target }}" >> $GITHUB_ENV
            fi
          shell: msys2 {0}

branding:
    icon: 'package'
    color: 'purple'
    