name: 'Arturo Bundler'
description: 'Bundle Arturo applications as executable binaries'
inputs:
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    arch:
        description: >-
            The architecture to build for.
            (one of: 'x86', 'arm', 'arm64', 'amd64', 'native')
        default: 'native'
    entry: 
        description: >-
            Entry file for the executable.
        required: true
    target:
        description: >-
            The name of the final binary.
        default: 'auto'
    version:
        description: >-
            The version - in case you want to include it in the archive names.
        default: ''
    release:
        description: >-
            Set to true, if it's running in a release build, to automatically package all assets.
        default: 'false'
    release_description:
        description: >-
            The body for the releases (if `release` is set). If this is not set, then the `github.ref` will be used.
        default: ''
runs:
    using: "composite"
    steps:
        - name: Install Arturo
          uses: arturo-lang/arturo-action@main
          with: 
            token: ${{ inputs.token }}
            arch: ${{ inputs.arch }}

        - name: Generate executable
          run: |
            if [ "${{ runner.os }}" = "Windows" ]; then
                export PATH="${{ github.workspace }}/nim/nim-2.0.4/bin":$PATH
            fi

            if [ "${{ inputs.target }}" = "auto" ]; then
                arturo --bundle ${{ inputs.entry }}
                entry="${{ inputs.entry }}"
                xbase=${entry##*/}
                xpref=${xbase%.*}

                if [ "${{ runner.os }}" != "Windows" ]; then
                    sudo chmod +x $xpref
                fi

                echo "EXEFILE=$xpref" >> $GITHUB_ENV
                echo "EXEFILE=$xpref" >> $GITHUB_OUTPUT
            else
                arturo --bundle --as:${{ inputs.target }} ${{ inputs.entry }}

                if [ "${{ runner.os }}" != "Windows" ]; then
                    sudo chmod +x ${{ inputs.target }}
                fi

                echo "EXEFILE=${{ inputs.target }}" >> $GITHUB_ENV
                echo "EXEFILE=${{ inputs.target }}" >> $GITHUB_OUTPUT
            fi

            if [[ "${{ runner.arch }}" = "ARM64" || "${{ inputs.arch }}" = "arm64" ]]; then
                echo "ARCHNAME=arm64" >> $GITHUB_ENV
            else
                echo "ARCHNAME=amd64" >> $GITHUB_ENV
            fi

            if [ "${{ inputs.version }}" != "" ]; then
                echo "VERS=-${{ inputs.version }}" >> $GITHUB_ENV
                echo "VERS=-${{ inputs.version }}" >> $GITHUB_OUTPUT
            else
                echo "VERS=" >> $GITHUB_ENV
                echo "VERS=" >> $GITHUB_OUTPUT
            fi

            if [ "${{ inputs.release }}" = "true" ]; then
                if [ "${{ inputs.version}}" != "" ]; then
                    ARCHV_VERS=$(arturo --evaluate "print replace {${{ github.ref_name }}} {/^v/} {}")
                    echo "VERS=$ARCHV_VERS" >> $GITHUB_ENV
                fi

                if [ "${{ inputs.release_description }}" = "" ]; then
                    echo "RELDESC=${{ github.ref }}" >> $GITHUB_ENV
                    echo "RELDESC=${{ github.ref }}" >> $GITHUB_OUTPUT
                else
                    echo "RELDESC=${{ inputs.release_description }}" >> $GITHUB_ENV
                    echo "RELDESC=${{ inputs.release_description }}" >> $GITHUB_OUTPUT
                fi

                echo "RELEASE=true" >> $GITHUB_OUTPUT
            else
                echo "RELEASE=false" >> $GITHUB_OUTPUT
            fi

            OSNAMELOWER=$(arturo --evaluate "print lower {${{ runner.os }}}")
            echo "OSNAME=$OSNAMELOWER" >> $GITHUB_ENV
          shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}

        - name: Create artifact
          run: |
            mkdir ${{ env.EXEFILE }}-${{ env.ARCHNAME }}-${{ env.OSNAME }}
            if [ "${{ runner.os }}" = "Windows" ]; then
                cp ${{ env.EXEFILE }}.exe ${{ env.EXEFILE }}-${{ env.ARCHNAME }}-${{ env.OSNAME }}
            else
                cp ${{ env.EXEFILE }} ${{ env.EXEFILE }}-${{ env.ARCHNAME }}-${{ env.OSNAME }}
            fi
          shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}

        - name: Upload Artifact
          uses: 'actions/upload-artifact@v4'
          with:
            name: ${{ env.EXEFILE }}${{ env.VERS }}-${{ env.ARCHNAME }}-${{ env.OSNAME }}
            path: ${{ env.EXEFILE }}-${{ env.ARCHNAME }}-${{ env.OSNAME }}    

branding:
    icon: 'package'
    color: 'purple'
    