name: 'Arturo Bundler'
description: 'Bundle Arturo applications as executable binaries'
branding:
    icon: package
    color: purple
inputs:
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    os:
        description: >-
            Target OS (linux, windows, macos, freebsd).
            Defaults to auto-detect from runner.
        default: ''
    arch:
        description: >-
            The architecture to build for.
            (one of: 'amd64', 'arm64', 'native')
        default: 'native'
    from:
        description: >-
            Arturo source (stable, latest, master).
            stable = latest official release, latest = nightly, master = compile from source.
        default: 'stable'
    entry: 
        description: >-
            Entry file for the executable.
        required: true
    target:
        description: >-
            The name of the final binary.
        default: 'auto'
    version:
        description: >-
            The version - in case you want to include it in the archive names.
        default: ''
    release:
        description: >-
            Prepare for release.
        default: 'false'
runs:
    using: "composite"
    steps:
        ######################################
        ######################################
        ## INITIAL SETUP
        ######################################
        ######################################

        - name: Detect build configuration
          run: |
            # Detect OS
            if [ -z "${{ inputs.os }}" ]; then
                case "${{ runner.os }}" in
                    Linux)   detected_os="linux" ;;
                    macOS)   detected_os="macos" ;;
                    Windows) detected_os="windows" ;;
                    *)       detected_os="linux" ;;
                esac
            else
                detected_os="${{ inputs.os }}"
            fi

            # Detect architecture
            if [ "${{ inputs.arch }}" = "native" ] || [ -z "${{ inputs.arch }}" ]; then
                case "${{ runner.arch }}" in
                    ARM64) detected_arch="arm64" ;;
                    X64)   detected_arch="amd64" ;;
                    *)     detected_arch="amd64" ;;
                esac
            else
                detected_arch="${{ inputs.arch }}"
            fi

            # Export to environment
            echo "os=$detected_os" >> $GITHUB_ENV
            echo "arch=$detected_arch" >> $GITHUB_ENV
          shell: bash

        ######################################
        ######################################
        ## DEPENDENCIES
        ######################################
        ######################################

        - name: Install Arturo
          uses: arturo-lang/setup-arturo@v2
          with: 
            token: ${{ inputs.token }}
            os: ${{ env.os }}
            arch: ${{ env.arch }}

        - name: Install Nim (Linux)
          if: env.os == 'linux'
          run: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo >> /home/runner/.bashrc
            echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew install nim
            echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          shell: bash

        - name: Install Nim (macOS)
          if: env.os == 'macos'
          run: |
            brew update
            brew install nim
          shell: bash

        - name: Install Nim (Windows)
          if: env.os == 'windows'
          run: |
            mkdir nim
            curl -L https://nim-lang.org/download/nim-2.2.6_x64.zip -o nim.zip
            7z x nim.zip -onim
            rm nim.zip
          shell: msys2 {0}

        - name: Install Nim (FreeBSD)
          if: env.os == 'freebsd'
          shell: freebsd {0}
          run: |
            pkg install -y nim git zip

        ######################################
        ######################################
        ## COMPILATION
        ######################################
        ######################################

        - name: Bundle
          shell: ${{ (env.os == 'freebsd') && 'freebsd {0}' || (env.os == 'windows') && 'msys2 {0}' || 'bash' }}
          run: |
            cd $GITHUB_WORKSPACE
            
            # Set up PATH for different platforms
            if [ "${{ env.os }}" = "windows" ]; then
                export PATH="${{ github.workspace }}/nim/nim-2.2.6/bin":$PATH
            elif [ "${{ env.os }}" = "freebsd" ]; then
                export PATH="/usr/local/nim/bin:$PATH"
            fi
            
            # Bundle
            if [ "${{ inputs.target }}" = "auto" ]; then
                arturo --bundle ${{ inputs.entry }}
                entry="${{ inputs.entry }}"
                xbase=${entry##*/}
                EXEFILE=${xbase%.*}
                if [ "${{ env.os }}" != "windows" ]; then
                    chmod +x $EXEFILE
                fi
            else
                arturo --bundle --as:${{ inputs.target }} ${{ inputs.entry }}
                EXEFILE="${{ inputs.target }}"
                if [ "${{ env.os }}" != "windows" ]; then
                    chmod +x $EXEFILE
                fi
            fi
            
            # Determine names
            OSNAME=$(arturo --evaluate "print lower {${{ env.os }}}")
            
            if [ "${{ inputs.version }}" != "" ]; then
                VERSION="-${{ inputs.version }}"
            else
                VERSION=""
            fi
            
            FILENAME="${EXEFILE}${VERSION}-${OSNAME}-${{ env.arch }}"
            
            # Create archive with just the binary
            if [ "${{ inputs.release }}" = "true" ]; then
                if [ "${{ env.os }}" = "windows" ]; then
                    7z a $FILENAME.zip ${EXEFILE}.exe
                else
                    zip $FILENAME.zip $EXEFILE
                fi
            fi
            
            # Save for later steps
            if [ "${{ env.os }}" = "freebsd" ]; then
                echo "$FILENAME" > .bundler_filename
                echo "$EXEFILE" > .bundler_exefile
            else
                echo "FILENAME=$FILENAME" >> $GITHUB_ENV
                echo "EXEFILE=$EXEFILE" >> $GITHUB_ENV
                echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
            fi

        ######################################
        ######################################
        ## ARTIFACTS
        ######################################
        ######################################

        - name: Copy FreeBSD artifacts to host
          if: env.os == 'freebsd'
          run: |
            # First, copy metadata files
            rsync -av -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
              freebsd:$GITHUB_WORKSPACE/.bundler_exefile freebsd:$GITHUB_WORKSPACE/.bundler_filename . || true
            
            # Read the metadata
            EXEFILE=$(cat .bundler_exefile)
            FILENAME=$(cat .bundler_filename)
            
            # Now copy the actual artifacts using the metadata
            rsync -av -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
              freebsd:$GITHUB_WORKSPACE/${EXEFILE}* . || true
            
            # Set environment for subsequent steps
            echo "FILENAME=$FILENAME" >> $GITHUB_ENV
            echo "EXEFILE=$EXEFILE" >> $GITHUB_ENV
            echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
          shell: bash

        - name: Upload Artifact
          if: inputs.release == 'true'
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.FILENAME }}
            path: ${{ env.FILENAME }}.zip