name: 'Subaction'
description: 'Release Arturo Bundle'
inputs:
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    bundling:
        description: >-
            The architecture to build for.
            (one of: 'x86', 'arm', 'arm64', 'amd64', 'native')
        required: true
runs:
    using: "composite"
    steps:
      - name: Download Artifact
        if: ${{ inputs.bundling.RELEASE == 'true' }}
        uses: actions/download-artifact@v2
        with:
            path: ./assets

      - name: Create Release
        if: ${{ inputs.bundling.RELEASE == 'true' }}
        id: create-release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ inputs.token }}
            EXEFILE: ${{ needs.test.outputs.EXEFILE }}
            VERS: ${{ needs.test.outputs.VERS }}
            RELDESC: ${{ needs.test.outputs.RELDESC }}
        with:
            tag_name: ${{ github.ref_name }}
            release_name: "${{ inputs.bundling.EXEFILE }} ${{ inputs.bundling.VERS }}"
            body: |
                ${{ inputs.bundling.EXEFILE }} ${{ inputs.bundling.VERS }} Release
                ${{ inputs.bundling.RELDESC }}
            draft: false
            prerelease: false
        
      - name: Upload Release Assets
        if: ${{ inputs.bundling.RELEASE == 'true' }}
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
            GITHUB_TOKEN: ${{ inputs.token }}
        with:
            release_id: ${{ steps.create-release.outputs.id }}
            assets_path: ./assets  

branding:
    icon: 'package'
    color: 'purple'
    