name: Release Arturo app

on:
  push:
    tags:
      - 'v*.*.*'

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
 
jobs:
    Bundle:
        runs-on: ubuntu-latest
        # ${{ matrix.os }}
        # strategy:
        #     matrix:
        #         os:
        #             - ubuntu-latest
        #             # - {os: macos-12}
        #             # - {os: macos-latest}
        #             # - {os: windows-latest}
        steps:
            - uses: actions/checkout@v4
            - uses: ./
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                entry: tests/testbundle.art
                version: 1.0.0
    
    Release:
        runs-on: ubuntu-latest
        if: ${{ always() }}
        needs: Bundle
        steps:
            - uses: arturo-lang/bundler-releases@main
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                name: ${{ needs.Bundle.outputs.EXEFILE }}
                version: ${{ needs.Bundle.outputs.VERSION }}
                 

