name: Release Arturo app

on:
  push:
    tags:
      - 'v*.*.*'

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
 
jobs:
    Bundle:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest 
                    - macos-12              # amd64
                    - macos-latest          # arm64 / M1
                    - windows-latest
        outputs:
            EXEFILE: ${{ steps.bundler.outputs.EXEFILE }}
            VERSION: ${{ steps.bundler.outputs.VERSION }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./
              id: bundler
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                entry: tests/testbundle.art
                version: 1.0.0
    
    Release:
        runs-on: ubuntu-latest
        if: ${{ always() }}
        needs: Bundle
        steps:
            - uses: arturo-lang/bundler-releases@main
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                name: ${{ needs.Bundle.outputs.EXEFILE }}
                version: ${{ needs.Bundle.outputs.VERSION }}
                 

