name: build

on:
    push:
        paths-ignore:
            - 'LICENSE'
            - '*.md'
        branches:
            - main
    pull_request:
        paths-ignore:
            - 'LICENSE'
            - '*.md'
    workflow_dispatch:

jobs:
    crossplatform-tester:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    #- windows-latest
                    - macOS-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}