name: build

on:
    push:
        paths-ignore:
            - 'LICENSE'
            - '*.md'
        branches:
            - main
    pull_request:
        paths-ignore:
            - 'LICENSE'
            - '*.md'
    workflow_dispatch:

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    crossplatform-tester:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - {os: ubuntu-latest}
                    - {os: macos-12}
        steps:
            - uses: actions/checkout@v4

            - uses: ./
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                entry: tests/testbundle.art

            - name: Run tests
              run: |
                ./testbundle
              shell: bash
            