name: build

on:
    push:
        paths-ignore:
            - 'LICENSE'
            - '*.md'
        branches:
            - main
    pull_request:
        paths-ignore:
            - 'LICENSE'
            - '*.md'
    workflow_dispatch:

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    crossplatform-tester:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macOS-12
                    - macOS-14
                mode:
                    - full
                    - mini
        steps:
            - uses: actions/checkout@v4
            - uses: ./
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                mode: ${{ matrix.mode }}

            - if: matrix.os == 'windows-latest'
              name: Run tests (Windows)
              run: |
                echo "Current directory:"
                pwd
    
                echo "Current path:"
                echo $PATH
    
                echo "Current GITHUB_PATH:"
                echo $GITHUB_PATH
                #echo "$HOME/.arturo/bin" >> $GITHUB_PATH
                #ls $HOME/.arturo
                #ls $HOME/.arturo/bin
                arturo -v
                arturo tests/test.art
                shell: bash
  
            - if: matrix.os != 'windows-latest'
              name: Run tests (*nix)
              run: |
                arturo -v
                arturo tests/test.art
              shell: bash

            